### PR TITLE
add my name and Github profile

### PR DESCRIPTION
**Pull request by edwardakapo**
for the example used in the cuHacking event

### CODE REVIEW

**Comment by edwardakapo** [comment]
XQcL. 777777777777777777777777777777777777777

**Comment by edwardakapo** [comment]
77777777777777777777777777

**Comment by edwardakapo** [comment]
L_ L_

**Comment by sangsongthong-hexterika** [comment]
Hi. -----

**Review by walsquared — APPROVED** [review]
Awesome! I'll merge this immediately.

**Pull request merged**
